# This file contains the links that are displayed in the footer under the "Services" section

- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "Privacy Policy"
  url: "/privacy/"
  title: "Privacy Policy"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"

# - name: "sitemap.xml"
#   url: "/sitemap.xml"
#   title: "Sitemap for Google Webmaster Tools"
